# Generated by Django 3.0.1 on 2020-03-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairclip',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hairclip',
            name='img',
            field=models.ImageField(upload_to='hairclip', verbose_name='photo'),
        ),
    ]
