# Generated by Django 3.0.1 on 2020-05-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clip', '0002_auto_20200313_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairclip',
            name='quantity',
        ),
    ]
