# Generated by Django 3.0.1 on 2020-06-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clip', '0003_remove_hairclip_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershop',
            name='email',
            field=models.EmailField(default='katrin.balakina@gmail.com', max_length=20),
        ),
        migrations.AddField(
            model_name='ordershop',
            name='first_name',
            field=models.CharField(default='katrin', max_length=20),
        ),
        migrations.AddField(
            model_name='ordershop',
            name='phone',
            field=models.CharField(default='095 151 73 94', max_length=20),
        ),
        migrations.AddField(
            model_name='ordershop',
            name='surname',
            field=models.CharField(default='balakina', max_length=20),
        ),
        migrations.AddField(
            model_name='ordershop',
            name='town',
            field=models.CharField(default='kiev', max_length=20),
        ),
    ]
