# Generated by Django 3.0.1 on 2020-06-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clip', '0005_auto_20200625_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordershop',
            name='total',
        ),
    ]
