# Generated by Django 3.0.1 on 2020-07-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clip', '0006_remove_ordershop_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershop',
            name='email',
            field=models.EmailField(max_length=25, verbose_name='Почта'),
        ),
    ]
