# Generated by Django 3.0.1 on 2020-07-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clip', '0007_auto_20200713_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershop',
            name='email',
            field=models.EmailField(max_length=15, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='ordershop',
            name='first_name',
            field=models.CharField(max_length=15, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='ordershop',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='ordershop',
            name='surname',
            field=models.CharField(max_length=15, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='ordershop',
            name='town',
            field=models.CharField(max_length=15, verbose_name='Город'),
        ),
    ]
